name: nacos.io deploy on OSS

on:
  push:
    branches:
      - develop-astro-nacos
jobs:
  Build-Deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install
        run: |
          npm install && npm i @swc/core@1.6.0
      - name: Build
        run: npm run build
      - name: Install Aliyun CLI
        run: |
          curl -O https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz
          tar -xzf aliyun-cli-linux-latest-amd64.tgz
          chmod +x aliyun
          ./aliyun version
      - name: Sync to OSS
        run: ./aliyun oss cp ./dist oss://nacos-website-cn-hongkong/ --meta Cache-Control:"max-age=3600" -r -f -e oss-cn-hongkong.aliyuncs.com --access-key-id ${{ secrets.ACCESS_KEYID }} --access-key-secret ${{ secrets.ACCESS_KEYSECRET }} --region cn-hongkong
